[project]
name = "mcp-server-template"
version = "0.1.0"
description = "A template for creating Model Context Protocol (MCP) servers"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.10.1",
]
